version: '3'
services:
  bitcoind:
    image: lncm/bitcoind:v26.0
    container_name: bitcoind
    restart: on-failure
    stop_grace_period: 30s
    user: 0:0
    healthcheck:
      test: ["CMD", "bitcoin-cli", "getinfo"]
    volumes:
      - ./configs/bitcoind.conf:/root/.bitcoin/bitcoin.conf
      - ./volumes.dev/bitcoind:/root/.bitcoin
    entrypoint:
        - "sh"
        - "-c"
        - "bitcoind"
    ports:
      - 18443:18443
      - 18444:18444

  faucet:
    depends_on:
      - bitcoind
    image: ghcr.io/velnbur/bitcoin-faucet:latest
    container_name: faucetd
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ./volumes.dev/faucetd:/root/bitcoin-faucet
      - ./configs/faucetd.toml:/etc/bitcoin-faucet/config.toml
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:18777/health"]
    environment:
      - RUST_BACKTRACE=1
    ports:
      - 18777:18777

volumes:
  bitcoind:
  # faucet:
