name: Check CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/nix-setup
      - name: Run `nix check`
        run: nix flake check
