name: Release CI

on:
  release:
    types: [created]

jobs:
  build-image:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run `nix build`
        run: nix build .#docker
      - name: Load Docker image
        run: docker load < result
      - name: Tag Docker image
        run: docker tag ghcr.io/velnbur/bitcoin-faucet:latest ghcr.io/velnbur/bitcoin-faucet:${{ github.ref_name }}
      - name: Push Docker image
        run: docker push ghcr.io/velnbur/bitcoin-faucet:${{ github.ref_name }}
